Repository ansys/pyconceptev, pull requests merged in 2024-07, with the labels that each got.

#77 updated example to match api changes
  examples/simple_workflow.py
  poetry.lock
  pyproject.toml
Labels: bug, maintenance

#80 slowed down pinging the results server
  doc/changelog.d/80.fixed.md
  examples/simple_workflow.py
Labels: bug

#78 ansys id login
  doc/changelog.d/78.added.md
  doc/source/user_guide.rst
  doc/styles/config/vocabularies/ANSYS/accept.txt
  examples/simple_workflow.py
  poetry.lock
  pyproject.toml
  src/ansys/conceptev/core/app.py
  src/ansys/conceptev/core/auth.py
  src/ansys/conceptev/core/resources/config.toml
  tests/test_app.py
  tests/test_auth.py
Labels: enhancement, maintenance, testing

#88 Fix/documentation links
  README.rst
  doc/changelog.d/88.fixed.md
  doc/source/getting_started.rst
Labels: bug

#94 CHORE: Bump dev version to 0.3.dev0
  doc/changelog.d/94.changed.md
  pyproject.toml
Labels: maintenance
