Repository ansys/pyconceptev, pull requests merged in 2024-11, with the labels that each got.

#131 added a get_concept function
  doc/changelog.d/131.added.md
  src/ansys/conceptev/core/app.py
Labels: enhancement

#136 improve test that was calling out to external endpoint
  doc/changelog.d/136.added.md
  examples/simple_workflow.py
  tests/test_app.py
Labels: enhancement, testing

#133 CI: Remove index jobs
  .github/workflows/ci_cd.yml
  doc/changelog.d/133.maintenance.md
Labels: maintenance

#141 update to remove security issues
  doc/changelog.d/141.maintenance.md
  poetry.lock
Labels: maintenance

#142 feature/account_checking
  doc/changelog.d/142.added.md
  src/ansys/conceptev/core/app.py
  src/ansys/conceptev/core/resources/test_config.toml
  tests/test_app.py
Labels: enhancement, testing

#148 added additional auth check on get results
  doc/changelog.d/148.fixed.md
  examples/simple_workflow.py
  src/ansys/conceptev/core/app.py
  src/ansys/conceptev/core/auth.py
Labels: bug

#147 CHORE: Bump dev version into 0.7.dev0
  doc/changelog.d/147.maintenance.md
  pyproject.toml
Labels: maintenance

#155 added a product_id to create_new_concept so it doesn't call ocm to often
  doc/changelog.d/155.fixed.md
  examples/simple_workflow.py
  src/ansys/conceptev/core/app.py
  tests/test_app.py
Labels: bug, testing

#156 added gateway timeout exception for get_results function
  doc/changelog.d/156.fixed.md
  src/ansys/conceptev/core/app.py
Labels: bug
